# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 14:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('object_id', models.IntegerField()),
                ('comment', models.TextField()),
                ('submit_date', models.DateTimeField(default=datetime.datetime.now)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('public', models.BooleanField(default=True)),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                   to=settings.AUTH_USER_MODEL)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
